# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: 5
  username: resumekey
  password: hippo1

development:
  <<: *default
  database: resumekey_development

test:
  <<: *default
  database: resumekey_test

production:
  adapter: postgresql
  pool: 5
  database: resumekey_production
